services:
  - type: web
    name: backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false   # set in Render dashboard
